[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32 BLE Arduino
; --- Cấu hình tối ưu cho bộ nhớ N16R8 ---
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv

build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_HAS_PSRAM

    ; Tắt 2 cờ dưới đây (thêm dấu ; ở đầu dòng) nếu bạn cắm cáp vào cổng "UART"
    ; Chỉ bật khi bạn cắm cáp vào cổng "USB" (Native USB) của mạch ESP32-S3
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1